// Generated by CoffeeScript 1.4.0
(function() {
  var ImageHeaders;

  ImageHeaders = (function() {

    function ImageHeaders() {}

    return ImageHeaders;

  })();

  module.exports = ImageHeaders;

}).call(this);
